### PR TITLE
Merge Tim's changes

### PR DESCRIPTION
**Pull request by ambit-developer**
Pull in all changes made by @TimOPI from 10/19–10/26.

Exception: preserves `SchoolYear` component and corresponding `schoolYear` function, which should be used to ensure auto-displaying of accurate school year without need for annual code changes.

### CODE REVIEW

**Comment by ambit-developer** [comment]
@rcoop017 — look good to you?

**Comment by TimOPI** [comment]
Thanks for reviewing the changes.

Can you confirm that the school year function will not change the school year on Jan 1?

Our concern was, come Jan 1 2017, the application’s school year variable will read: 2017/2018 (or any variation of that “17/18”).

**Comment by rcoop017** [comment]
Yep. Looks good.

**Comment by ambit-developer** [comment]
@TimOPI — what's the desired behavior (when should the system tick over to the next school year)? Asked a different way: what is the latest point in a given school year that a family might apply for free/reduced lunch?

**Comment by ambit-developer** [comment]
Merging.

Opened issue #6 to track the auto-advancing school year discussion.

**Pull request merged**
