### PR TITLE
Localize

### LINKED ISSUE #64: Localize remaining strings
A handful of English strings haven't been localized (primarily form labels, it looks like).

Details:

[NSLP-Missing-Textual-Elements-20161116.docx](https://github.com/The-Ambit-Group/school-meals/files/597879/NSLP-Missing-Textual-Elements-20161116.docx)

### PR DESCRIPTION
**Pull request by ambit-developer**
Resolves #64

### CODE REVIEW

**Comment by rcoop017** [comment]
Does this fix the missing Help topics? Or should I open a new Issue for that? Still can't find where that text lives...

**Comment by TimOPI** [comment]
@rcoop017 Should HelpText.jsx be handled in the same way Tooltiptext.jsx is?

In other words, all the tooltip variables are set up for formattedmessage, but helptext is not.

I can jump in and set all of those up, if that's why the help items are getting localized.

**Comment by rcoop017** [comment]
@TimOPI where IS the HelpText.jsx? Also, yes. As soon as I look at the file I can give you a definite answer.

**Comment by ambit-developer** [comment]
@TimOPI, @rcoop017 — see #0715083 for beginnings.

**Comment by ambit-developer** [comment]
Also @rcoop017 @TimOPI — you can run `npm run build-language` to auto-generate `EMPTY.json`

**Comment by rcoop017** [comment]
Excellent! Thanks!

**Pull request merged**
